server:
  port: 8001 # 如改为0，即随机分配可用端口

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.merlin.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: dept-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/superetail              # 数据库名称
    # jdbc:mysql://localhost:3306/superetail?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: merlin
    password: helloworld
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #单机注册
      defaultZone: http://merlin:helloworld@eureka7001.com:7001/eureka/
      #集群注册       项目代码一模一样 只修改端口号
      #defaultZone: http://eureka7001.com:7001/eureka/,
      # http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    #instance-id: provider-dept8001
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    #访问路径可以显示IP地址
    prefer-ip-address: true

# 要在Eureka(http://host:port/actuator/info)展示实例信息，增加依赖spring-boot-starter-actuator
info:
  app.name: service-provider
  company.name: www.phenix.com
  # NOTE: 通过@*@来获取Maven里的属性值，依赖spring-cloud-commons
  build.artifactId: @project.artifactId@
  build.version: @project.version@