server:
  port: 8098

spring:
  application:
    name: dept-consumer
#  main:
#    allow-bean-definition-overriding: true

# FeignClient配置，并启用Hystrix
feign:
  client:
    config:
      dept-provider:           #服务名，default为所有服务
        connectTimeout: 10000
        readTimeout: 12000
  hystrix:
    enabled: true             #启用hystrix

eureka:
  client:
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://merlin:helloworld@eureka7001.com:7001/eureka/
  instance:
    #instance-id: provider-dept8001
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    #访问路径可以显示IP地址
    prefer-ip-address: true

# 要在Eureka(http://host:port/actuator/info)展示实例信息，增加依赖spring-boot-starter-actuator
info:
  app.name: service-consumer
  company.name: www.phenix.com
  # NOTE: 通过@*@来获取Maven里的属性值, 依赖spring-cloud-commons
  build.artifactId: @project.artifactId@
  build.version: @project.version@