server:
  port: 7001

# 微服务的名称 - 注册中心本身就是一个微服务
spring:
  application:
    name: merlin-eureka
  # 自定义的用户名和密码
  security:
    user:
      name: merlin
      password: helloworld

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    # 当前的微服务是否注册到eureka上，默认为true
    register-with-eureka: false     #false表示不向注册中心注册自己。
    # 当前微服务是否可以调用其他微服务，默认为true
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # NOTE: 设置密码后调整的url
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

      #集群
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
